# install.packages("bbmle", lib="Rpackages")
install.packages("deSolve")
install.packages("doMC")
install.packages("foreach")
# install.packages("emdbook", lib="Rpackages")
install.packages("GillespieSSA")
# install.packages("assertive")
